#!/bin/sh
USERS=$(lslogins --noheadings -u -o user | grep -vw root)

for USER in $USERS
do
  # Remove user contab entry
  crontab -u $USER -l | sed '\;/usr/bin/mx-alerts.sh;d'  | crontab -u $USER -
done

#DEBHELPER#
